#!/usr/bin/env python3
"""Generate the shared JSON-LD blocks for every page from one source of truth.

This site has no build step, so "shared include" here means authored once and
stamped in mechanically, rather than copy-pasted per page. Business identity
(NAP, geo, opening hours, areaServed, sameAs) lives only in
seo/schema/business.json. Running this script rewrites the managed block on
every page between the markers below; nothing else on the page is touched.

Run from the repo root:  python3 seo/build-schema.py [--check]

--check exits non-zero if any page is out of date, for use in CI.

Deliberately never emitted: aggregateRating and review. The business has no
verified review data, and fabricated review markup risks a manual action. This
script strips both from every JSON-LD block on every page, including the
page-owned Product blocks it otherwise leaves alone.
"""
import json, re, sys, glob, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://mahadev-traders.com"
START, END = "<!-- seo:schema:start (generated by seo/build-schema.py - do not edit) -->", "<!-- seo:schema:end -->"
BANNED = ("aggregateRating", "review", "reviewCount", "ratingValue")
# Types this script owns. Any pre-existing block of these types is replaced, so a
# page can never end up with two BreadcrumbLists or two Organization blocks.
MANAGED_TYPES = ("BreadcrumbList", "WebSite", "Organization", "LocalBusiness")

# Range page each product page sits under, for the breadcrumb trail.
CATEGORY_OF = {}
CATEGORIES = {
 "Plywood": ("/products/plywood-wholesaler-rajkot.html", [
   "/products/marine-plywood-710-rajkot.html","/products/commercial-plywood-mr-grade.html",
   "/products/gurjan-plywood-dealer.html","/products/shuttering-plywood-construction.html",
   "/products/flexible-plywood-supplier.html","/products/greytone-plywood-dealers.html",
   "/products/limelite-plywood-supplier.html","/products/marllex-premium-plywood.html",
   "/products/simson-plywood-supplier.html","/products/zevik-plywood-supplier.html"]),
 "Block Board": ("/products/block-board-wholesale-supplier.html", [
   "/products/poplar-block-board.html","/products/pine-wood-block-board.html",
   "/products/bwp-waterproof-block-board.html","/products/gurjan-block-board-dealer.html",
   "/products/marllex-block-board-premium.html"]),
 "Laminates": ("/products/decorative-laminates-sheets.html", [
   "/products/sunmica-dealers-rajkot.html","/products/liner-laminates-inner.html"]),
 "Flush Doors": ("/products/flush-doors-manufacturer-supplier.html", [
   "/products/waterproof-flush-doors-bwp.html","/products/laminated-flush-doors-designs.html",
   "/products/pine-wood-flush-doors.html","/products/waterproof-bathroom-doors.html",
   "/products/marllex-flush-doors-premium.html"]),
 "MDF & HDHMR": ("/products/mdf-wholesale-rajkot.html", [
   "/products/motherwood-mdf-rajkot.html","/products/hdhmr-board-supplier-rajkot.html",
   "/products/mdf-interior-exterior-grade-rajkot.html","/products/motherwood-mdf-turbo-plus.html",
   "/products/motherwood-mdf-super-hd-wr.html","/products/motherwood-mdf-exterior-grade.html"]),
}
for cat, (hub, kids) in CATEGORIES.items():
    CATEGORY_OF[hub] = (cat, hub, True)
    for k in kids:
        CATEGORY_OF[k] = (cat, hub, False)


def normalise_seller(node):
    """Point every Product.seller / Service.provider at the single source of truth.

    Keeps the details inline rather than using a bare @id reference, because
    cross-page @id resolution is unreliable, but regenerates them from
    business.json so a phone or address change propagates to every page instead
    of needing an edit on each one. This is what keeps NAP consistent.
    """
    b = json.load(open(os.path.join(ROOT, "seo/schema/business.json"), encoding="utf-8"))
    seller = {"@type": "LocalBusiness", "@id": BASE + "/#business", "name": b["name"],
              "telephone": b["telephone"], "email": b["email"], "url": b["url"],
              "address": b["address"]}
    if isinstance(node, dict):
        out = {}
        for k, v in node.items():
            if k in ("seller", "provider") and isinstance(v, dict) and \
               v.get("@type") in ("LocalBusiness", "Organization", "Store"):
                out[k] = dict(seller)
            else:
                out[k] = normalise_seller(v)
        return out
    if isinstance(node, list):
        return [normalise_seller(x) for x in node]
    return node


def strip_banned(node):
    """Remove aggregateRating / review anywhere in the tree."""
    if isinstance(node, dict):
        return {k: strip_banned(v) for k, v in node.items() if k not in BANNED}
    if isinstance(node, list):
        return [strip_banned(x) for x in node]
    return node


def biz(short=False):
    b = json.load(open(os.path.join(ROOT, "seo/schema/business.json"), encoding="utf-8"))
    if short:
        return {"@type": "LocalBusiness", "@id": BASE + "/#business",
                "name": b["name"], "telephone": b["telephone"], "address": b["address"]}
    return {
        "@context": "https://schema.org", "@type": "LocalBusiness", "@id": BASE + "/#business",
        "name": b["name"], "description": b["description"], "url": b["url"],
        "image": b["image"], "telephone": b["telephone"], "email": b["email"],
        "priceRange": b["priceRange"], "foundingDate": b["foundingDate"],
        "address": b["address"], "geo": b["geo"],
        "openingHoursSpecification": b["openingHoursSpecification"],
        "areaServed": [{"@type": "City", "name": a} for a in b["areaServed"]],
        "sameAs": b["sameAs"],
    }


def page_name(html, rel):
    m = re.search(r"<h1>(.*?)</h1>", html, re.S)
    if m:
        t = re.sub(r"<[^>]+>", " ", m.group(1))
        t = re.sub(r"\s+", " ", t).strip(" -–—|")
        if t:
            return t
    t = re.search(r"<title>(.*?)</title>", html, re.S).group(1)
    return t.split("|")[0].strip()


def breadcrumb(rel, html):
    items = [("Home", BASE + "/")]
    if rel.startswith("products/"):
        items.append(("Products", BASE + "/products/"))
        site = "/" + rel
        cat = CATEGORY_OF.get(site)
        if cat and not cat[2]:
            hub = cat[1]
            hub_html = open(os.path.join(ROOT, hub.lstrip("/")), encoding="utf-8").read()
            items.append((cat[0], BASE + hub))
        if rel != "products/index.html":
            items.append((page_name(html, rel), BASE + "/" + rel))
    elif rel.startswith("services/"):
        items.append(("Services", BASE + "/services/"))
    elif rel != "index.html":
        items.append((page_name(html, rel), BASE + "/" + rel))
    return {"@context": "https://schema.org", "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": i + 1, "name": n, "item": u}
                for i, (n, u) in enumerate(items)]}


def managed(rel, html):
    b = json.load(open(os.path.join(ROOT, "seo/schema/business.json"), encoding="utf-8"))
    out = [breadcrumb(rel, html)]
    if rel == "index.html":
        out.append({"@context": "https://schema.org", "@type": "WebSite",
                    "@id": BASE + "/#website", "name": b["name"], "url": BASE + "/",
                    "publisher": {"@id": BASE + "/#organization"}})
        out.append({"@context": "https://schema.org", "@type": "Organization",
                    "@id": BASE + "/#organization", "name": b["name"],
                    "url": BASE + "/", "logo": b["image"], "email": b["email"],
                    "telephone": b["telephone"], "foundingDate": b["foundingDate"],
                    "address": b["address"], "sameAs": b["sameAs"]})
        out.append(biz())
    parts = [START]
    for o in out:
        parts.append('  <script type="application/ld+json">')
        parts.append(json.dumps(strip_banned(o), indent=2, ensure_ascii=False))
        parts.append("  </script>")
    parts.append("  " + END)
    return "\n  ".join(parts) + "\n"


def build(check=False):
    stale, done = [], 0
    for path in sorted(glob.glob(os.path.join(ROOT, "**/*.html"), recursive=True)):
        rel = os.path.relpath(path, ROOT)
        html = open(path, encoding="utf-8").read()
        orig = html

        # drop any previous managed region, whitespace included, so re-runs are no-ops
        html = re.sub(r"[ \t]*" + re.escape(START) + r".*?" + re.escape(END) + r"[ \t]*\n?",
                      "", html, flags=re.S)

        # rewrite the page-owned blocks: strip banned keys, drop managed types
        def fix(m):
            try:
                d = json.loads(m.group(1))
            except Exception:
                return m.group(0)
            items = d if isinstance(d, list) else [d]
            keep = [x for x in items if x.get("@type") not in MANAGED_TYPES]
            if not keep:
                return "__SEO_DROP__"
            out = normalise_seller(strip_banned(keep if isinstance(d, list) else keep[0]))
            return ('<script type="application/ld+json">\n'
                    + json.dumps(out, indent=2, ensure_ascii=False)
                    + "\n  </script>")
        html = re.sub(r'<script type="application/ld\+json">(.*?)</script>', fix, html, flags=re.S)
        html = re.sub(r"[ \t]*__SEO_DROP__[ \t]*\n?", "", html)

        blk = managed(rel, html)
        html = re.sub(r"\n</head>", "\n  " + blk + "</head>", html, count=1)

        if html != orig:
            stale.append(rel)
            if not check:
                open(path, "w", encoding="utf-8").write(html)
        done += 1
    return done, stale


if __name__ == "__main__":
    chk = "--check" in sys.argv
    n, stale = build(check=chk)
    print(f"pages processed: {n}")
    if chk:
        print(f"out of date: {len(stale)}")
        for s in stale:
            print("  ", s)
        sys.exit(1 if stale else 0)
    print(f"pages rewritten: {len(stale)}")
